class CONNECTION:
    LENGTHS = [3, 4, 5]


class MAP:
    MAX_WIDTH = 800
    MAX_HEIGHT = 800
    MIN_WIDTH = 10
    MIN_HEIGHT = 10


class GAME:
    NUM_DESTINATIONS_PER_PLAYER = 2
    INITIAL_NUM_RAILS = 45
    NUM_TOTAL_CARDS = 250

